package com.rentcar.rentcar.pojo;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone_name
     *
     * @mbggenerated
     */
    private String phoneName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.head
     *
     * @mbggenerated
     */
    private String head;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.card_class
     *
     * @mbggenerated
     */
    private String cardClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.card_num
     *
     * @mbggenerated
     */
    private String cardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_rentaling
     *
     * @mbggenerated
     */
    private String isRentaling;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_loging
     *
     * @mbggenerated
     */
    private String isLoging;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.register_time
     *
     * @mbggenerated
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone_name
     *
     * @return the value of user.phone_name
     *
     * @mbggenerated
     */
    public String getPhoneName() {
        return phoneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone_name
     *
     * @param phoneName the value for user.phone_name
     *
     * @mbggenerated
     */
    public void setPhoneName(String phoneName) {
        this.phoneName = phoneName == null ? null : phoneName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.head
     *
     * @return the value of user.head
     *
     * @mbggenerated
     */
    public String getHead() {
        return head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.head
     *
     * @param head the value for user.head
     *
     * @mbggenerated
     */
    public void setHead(String head) {
        this.head = head == null ? null : head.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.card_class
     *
     * @return the value of user.card_class
     *
     * @mbggenerated
     */
    public String getCardClass() {
        return cardClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.card_class
     *
     * @param cardClass the value for user.card_class
     *
     * @mbggenerated
     */
    public void setCardClass(String cardClass) {
        this.cardClass = cardClass == null ? null : cardClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.card_num
     *
     * @return the value of user.card_num
     *
     * @mbggenerated
     */
    public String getCardNum() {
        return cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.card_num
     *
     * @param cardNum the value for user.card_num
     *
     * @mbggenerated
     */
    public void setCardNum(String cardNum) {
        this.cardNum = cardNum == null ? null : cardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_rentaling
     *
     * @return the value of user.is_rentaling
     *
     * @mbggenerated
     */
    public String getIsRentaling() {
        return isRentaling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_rentaling
     *
     * @param isRentaling the value for user.is_rentaling
     *
     * @mbggenerated
     */
    public void setIsRentaling(String isRentaling) {
        this.isRentaling = isRentaling == null ? null : isRentaling.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_loging
     *
     * @return the value of user.is_loging
     *
     * @mbggenerated
     */
    public String getIsLoging() {
        return isLoging;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_loging
     *
     * @param isLoging the value for user.is_loging
     *
     * @mbggenerated
     */
    public void setIsLoging(String isLoging) {
        this.isLoging = isLoging == null ? null : isLoging.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.register_time
     *
     * @return the value of user.register_time
     *
     * @mbggenerated
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.register_time
     *
     * @param registerTime the value for user.register_time
     *
     * @mbggenerated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.level
     *
     * @return the value of user.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.level
     *
     * @param level the value for user.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}