package com.rentcar.rentcar.service;


import com.rentcar.rentcar.pojo.ManagerUser;
import com.rentcar.rentcar.pojo.ManagerUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ManagerUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated
     */
    int countByExample(ManagerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated
     */
    int deleteByExample(ManagerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated
     */
    int insert(ManagerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated
     */
    int insertSelective(ManagerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated
     */
    List<ManagerUser> selectByExample(ManagerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated
     */
    ManagerUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ManagerUser record, @Param("example") ManagerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ManagerUser record, @Param("example") ManagerUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManagerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManagerUser record);
}