package com.rentcar.rentcar.service;

import com.rentcar.rentcar.pojo.ManagerRoles;
import com.rentcar.rentcar.pojo.ManagerRolesExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ManagerRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    int countByExample(ManagerRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    int deleteByExample(ManagerRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    int insert(ManagerRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    int insertSelective(ManagerRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    List<ManagerRoles> selectByExample(ManagerRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    ManagerRoles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ManagerRoles record, @Param("example") ManagerRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ManagerRoles record, @Param("example") ManagerRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManagerRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManagerRoles record);
}